# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
#image: gradle:alpine
default:
  image: git.bio.informatik.uni-jena.de:5050/bioinf-mit/docker-images/ubuntu-zulu-fx-gradle:22.04-15.42.15-6.9.2-9
# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
stages:
  - clean
  - prepare
  - build
#  - build-cli
#  - build-multi-cli
#  - build-gui
  - publish

before_script:
  - dpkg-reconfigure -p critical ca-certificates
  - eval `ssh-agent -s`
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null # add ssh key
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$GITLAB_GITHUB_SIRIUS_PUBLIC_KEY" >> ~/.ssh/id_ed25519.pub
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

#clean:
#  stage: clean
#  script: gradle clean
#  cache:
#    key: "$CI_COMMIT_REF_NAME"
#    policy: push
#  tags:
#    - gradle

#todo re-enable doc build
#doc:
#  variables:
#    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.java.home=/vol/software/jvm/zulu14.29.23-ca-fx-jdk14.0.2-linux_x64"
#  stage: prepare
#  script:
#    - cd sirius_doc
#    - gradle clean artifactoryPublish
#  cache:
#    key: "$CI_COMMIT_REF_NAME"
#    policy: push
#  tags:
#    - artifactory
#    - gradle
#    - biber-latex
#  only:
#    refs:
#      - master
#      - stable
#    # stupid there is no exclude if only specific type was changed, so we have to use some heuristic to exclude README only changes
#    # from pipeline
#    changes:
#      - "sirius_doc/**/*"
#      - "sirius_cli/src/main/resources/sirius_frontend.build.properties"
#      - ".gitlab-ci.yml"

distCliLinux64:
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  stage: build
  script:
    - cd sirius_dist/sirius_cli_single_os
    - gradle clean artifactoryPublish --refresh-dependencies -P "de.unijena.bioinf.build.artifactory.username=$ARTIFACTORY_USERNAME" -P "de.unijena.bioinf.build.artifactory.password=$ARTIFACTORY_TOKEN"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
  tags:
    - kubernetes
  only:
    refs:
      - master
      - stable
    # stupid there is no exclude if only specific type was changed, so we have to use some heuristic to exclude README only changes
    # from pipeline
    changes:
      - "**/*.{java,gradle,properties,yml,tex,png,ico,json,xml,html,csv,tsv,py}"
      - "**/src/main/java/**/*"

distGuiLinux64:
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  stage: build
  script:
    - cd sirius_dist/sirius_gui_single_os
    - gradle clean artifactoryPublish --refresh-dependencies -P "de.unijena.bioinf.build.artifactory.username=$ARTIFACTORY_USERNAME" -P "de.unijena.bioinf.build.artifactory.password=$ARTIFACTORY_TOKEN"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
  tags:
    - kubernetes
  only:
    refs:
      - master
      - stable
    # stupid there is no exclude if only specific type was changed, so we have to use some heuristic to exclude README only changes
    # from pipeline
    changes:
      - "**/*.{java,gradle,properties,yml,tex,png,ico,json,xml,html,csv,tsv,py}"
      - "**/src/main/java/**/*"

distRestLinux64:
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  stage: build
  script:
    - cd sirius_dist/sirius_service_single_os
    - gradle clean artifactoryPublish --refresh-dependencies -P "de.unijena.bioinf.build.artifactory.username=$ARTIFACTORY_USERNAME" -P "de.unijena.bioinf.build.artifactory.password=$ARTIFACTORY_TOKEN"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
  tags:
    - kubernetes
  only:
    refs:
      - master
      - stable
    # stupid there is no exclude if only specific type was changed, so we have to use some heuristic to exclude README only changes
    # from pipeline
    changes:
      - "**/*.{java,gradle,properties,yml,tex,png,ico,json,xml,html,csv,tsv,py}"
      - "**/src/main/java/**/*"

#push to github for multiOS build
pushToGitHub:
  stage: publish
  script:
    - git config --global user.email "${GITLAB_GITHUB_SIRIUS_USERNAME}"
    - git config --global user.name "boeckergitlab"
    - git remote show origin
    - git remote set-url --push origin git@github.com:boecker-lab/sirius.git
    - git remote show origin
    - git push --follow-tags origin HEAD:$CI_COMMIT_REF_NAME
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
  tags:
    - kubernetes
  only:
    refs:
      - stable
      - master
#distCliWin64:
#  variables:
#    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
#  stage: build-cli
#  needs: ["doc"]
#  script:
#    - $env:path
#    - cd sirius_dist/sirius_cli_single_os
#    - gradle.bat artifactoryPublish --refresh-dependencies
#  cache:
#    key: "$CI_COMMIT_REF_NAME"
#    policy: push
#  tags:
#    - artifactory
#    - gradle
#    - windows64
#  only:
#    refs:
#      - master
#      - release-4
#
#distGuiWin64:
#  variables:
#    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
#  stage: build-gui
#  script:
#    - $env:path
#    - cd sirius_dist/sirius_gui_single_os
#    - gradle.bat clean artifactoryPublish --refresh-dependencies
#  cache:
#    key: "$CI_COMMIT_REF_NAME"
#    policy: push
#  tags:
#    - artifactory
#    - gradle
#    - windows64
#  only:
#    refs:
#      - master

#distCliMacOSX:
#  variables:
#    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.java.home=/Users/ladmin/gitlab/zulu14.29.23-ca-fx-jdk14.0.2-macosx_x64"
#  stage: build-cli
#  needs: ["doc"]
#  script:
#    - cd sirius_dist/sirius_cli_single_os
#    - /Users/ladmin/gitlab/gradle-6.6.1/bin/gradle artifactoryPublish --refresh-dependencies
#  cache:
#    key: "$CI_COMMIT_REF_NAME"
#    policy: push
#  tags:
#    - artifactory
#    - gradle
#    - macosx
#  only:
#    refs:
#      - master
#      - release-4
#
#distGuiMacOX:
#  variables:
#    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.java.home=/Users/ladmin/gitlab/zulu14.29.23-ca-fx-jdk14.0.2-macosx_x64"
#  stage: build-gui
#  needs: ["distCliMacOSX","doc"]
#  script:
#    - cd sirius_dist/sirius_gui_single_os
#    - /Users/ladmin/gitlab/gradle-6.6.1/bin/gradle artifactoryPublish --refresh-dependencies
#  cache:
#    key: "$CI_COMMIT_REF_NAME"
#    policy: push
#  tags:
#    - artifactory
#    - gradle
#    - macosx
#  only:
#    refs:
#      - master
#      - release-4
#
#distCliMultiOS:
#  variables:
#    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.java.home=/vol/software/jvm/zulu14.29.23-ca-fx-jdk14.0.2-linux_x64"
#  stage: build-multi-cli
#  needs: ["distCliWin64","distCliMacOSX","distCliLinux64"]
#  script:
#    - cd sirius_dist/sirius_cli_multi_os
#    - gradle artifactoryPublish --refresh-dependencies
#  cache:
#    key: "$CI_COMMIT_REF_NAME"
#    policy: push
#  tags:
#    - artifactory
#    - gradle
#    - linux64
#  only:
#    refs:
#      - master
#      - release-4