# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
#image: gradle:alpine
default:
  image: git.bio.informatik.uni-jena.de:5050/bioinf-mit/docker-images/ubuntu-zulu-fx-gradle:22.04-15.42.15-6.9.2-9
# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
stages:
  - clean
  - prepare
  - build
  - test
  - publish


before_script:
  - dpkg-reconfigure -p critical ca-certificates
  - eval `ssh-agent -s`
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null # add ssh key
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$GITLAB_GITHUB_SIRIUS_PUBLIC_KEY" >> ~/.ssh/id_ed25519.pub
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'


buildCLI:
  stage: build
  script:
    - gradle :sirius_dist:sirius_cli_single_os:distImage
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
  artifacts:
    paths:
      - ./sirius_dist/sirius_cli_single_os/build/distributions/sirius
  tags:
    - kubernetes
  only:
    refs:
      - master
      - stable


buildGUI:
  stage: build
  script:
    - gradle :sirius_dist:sirius_gui_single_os:distImage
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
  artifacts:
    paths:
      - ./sirius_dist/sirius_gui_single_os/build/distributions/sirius
  tags:
    - kubernetes
  only:
    refs:
      - master
      - stable


buildAPI:
  stage: build
  script:
    - gradle :sirius_dist:sirius_service_single_os:distImage
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
  artifacts:
    paths:
      - ./sirius_dist/sirius_service_single_os/build/distributions/sirius
  tags:
    - kubernetes
  only:
    refs:
      - master
      - stable


testCLI:
  stage: test
  script:
    - ./sirius_dist/sirius_cli_single_os/build/distributions/sirius/bin/sirius login --user-env SIRIUS_USER --password-env SIRIUS_PW
    - gradle :sirius_dist:sirius_cli_single_os:distImageTest
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
  needs: [buildCLI]
  dependencies:
    - buildCLI
  tags:
    - kubernetes
  only:
    refs:
      - master
      - stable


testGUI:
  stage: test
  script:
    - ./sirius_dist/sirius_gui_single_os/build/distributions/sirius/bin/sirius login --user-env SIRIUS_USER --password-env SIRIUS_PW
    - gradle :sirius_dist:sirius_gui_single_os:distImageTest
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
  needs: [buildGUI]
  dependencies:
    - buildGUI
  tags:
    - kubernetes
  only:
    refs:
      - master
      - stable


testAPI:
  stage: test
  script:
    - ./sirius_dist/sirius_service_single_os/build/distributions/sirius/bin/sirius login --user-env SIRIUS_USER --password-env SIRIUS_PW
    - gradle :sirius_dist:sirius_service_single_os:distImageTest
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
  needs: [buildAPI]
  dependencies:
    - buildAPI
  tags:
    - kubernetes
  only:
    refs:
      - master
      - stable


publishCLI:
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  stage: publish
  script:
    - cd sirius_dist/sirius_cli_single_os
    - gradle clean artifactoryPublish --refresh-dependencies -P "de.unijena.bioinf.build.artifactory.username=$ARTIFACTORY_USERNAME" -P "de.unijena.bioinf.build.artifactory.password=$ARTIFACTORY_TOKEN"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
  needs: [buildCLI, testCLI]
  dependencies:
    - buildCLI
  tags:
    - kubernetes
  only:
    refs:
      - master
      - stable


publishGUI:
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  stage: publish
  script:
    - cd sirius_dist/sirius_gui_single_os
    - gradle clean artifactoryPublish --refresh-dependencies -P "de.unijena.bioinf.build.artifactory.username=$ARTIFACTORY_USERNAME" -P "de.unijena.bioinf.build.artifactory.password=$ARTIFACTORY_TOKEN"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
  needs: [buildGUI, testGUI]
  dependencies:
    - buildGUI
  tags:
    - kubernetes
  only:
    refs:
      - master
      - stable

publishAPI:
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  stage: publish
  script:
    - cd sirius_dist/sirius_gui_single_os
    - gradle clean artifactoryPublish --refresh-dependencies -P "de.unijena.bioinf.build.artifactory.username=$ARTIFACTORY_USERNAME" -P "de.unijena.bioinf.build.artifactory.password=$ARTIFACTORY_TOKEN"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
  needs: [buildAPI, testAPI]
  dependencies:
    - buildAPI
  tags:
    - kubernetes
  only:
    refs:
      - master
      - stable

#push to github to build for multiple OSs
pushToGitHub:
  stage: publish
  script:
    - git config --global user.email "${GITLAB_GITHUB_SIRIUS_USERNAME}"
    - git config --global user.name "boeckergitlab"
    - git remote show origin
    - git remote set-url --push origin git@github.com:boecker-lab/sirius.git
    - git remote show origin
    - git push --follow-tags origin HEAD:$CI_COMMIT_REF_NAME
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
  needs: [testCLI, testGUI, testAPI]
  tags:
    - kubernetes
  only:
    refs:
      - stable
      - master